### ISSUE TITLE
Modal vertical positioning

### ISSUE THREAD

**Issue by trippo** [wireui/wireui#18]
I saw that the desktop version always positions the modal at the top.
Is it possible to set md:items-center?
I prefer to have a modal at the center of the screen.
If you think it's not like that, can you provide an option to do this?

**Comment by ph7jack** [comment]
I haven't put it in the documentation yet due to lack of time in the middle of the week, but in this last release I created options to configure the modal defaults, you can put in **env** or publish the configuration file and edit it, or simply pass **:align="center"** as prop in **modal** or **modal card**

https://github.com/PH7-Jack/wireui/blob/master/config/wireui.php
https://github.com/PH7-Jack/wireui/blob/master/src/View/Components/Modal.php

**Comment by trippo** [comment]
Amazing
