### ISSUE TITLE
use wireui in blade layouts

### ISSUE THREAD

**Issue by aliqasemzadeh** [wireui/wireui#31]
Hi 
When I want to use WireUI in layouts blade I get:
$_instance is undefined
Which mains we can not use wireui in blade layouts.

**Comment by ph7jack** [comment]
Hello @alighasemzadeh 

In blade layout theses components does't work:
- Maskable Input
- Phone Input
- Currency input
- Datetime Picker
- Time Picker
- Select

Not work because are using livewire @**entangle** directive to share model data with livewire component, so, is required be used inside a livewire

Why you need theses componentes outside a livewire componente?

**Comment by aliqasemzadeh** [comment]
For example we need global modal in layout.

**Comment by ph7jack** [comment]
You can put this modal inside a livewire component, and import this

Ex: 
```
layouts/app.blade.php

<html>
...
<body>
...
<livewire:login-modal />
...

{{ $slot }}
...
</html>
``` 

You can use livewire events to show modal when click in button in anywhere part of layout
Or create a button in modal component to show this modal

If need more details about implementation, send an email to schedule a call

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
I understand what to do.
